spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/core_form_service}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  flyway:
    enabled: true
app:
  export:
    template-path: ${EXPORT_TEMPLATE_PATH:classpath:export-template.xlsx}
